### ISSUE TITLE
Convert svg to gif to work on all browsers

### ISSUE THREAD

**Issue by eddiejaoude** [jh3y/jh3y#1]
Animations do not work on safari on Mac

**Comment by HansUXdev** [comment]
Use record it.co

**Comment by jh3y** [comment]
Animations can work in Safari. That said, it depends on the animation.

The first animation in [this tutorial](https://egghead.io/lessons/css-use-svg-with-inline-css-animations-to-personalize-your-github-profile) where the `fill` is animated, will work in Safari. But, I agree, the animation I have in my README, does not work in Safari and I've not looked into why yet 👎
